### PR TITLE
Improved language fallbacks in LocalizeStrings#localize: Try general …

### PR DESCRIPTION
**Pull request by tladesignz**
…language without region qualifier first, before falling back to default language.

### CODE REVIEW

**Comment by andresilvagomez** [comment]
@tladesignz that's amazing, could you please check the test?

**Comment by tladesignz** [comment]
The Travis tests? "Segmentation Fault 11". That doesn't look like that's an issue with the code. In my environment (Xcode 9.3 @ MacOS 10.13.4) the example app *and* the tests are building and running.

**Comment by tladesignz** [comment]
Don't know how to rerun them.

**Comment by andresilvagomez** [comment]
@tladesignz I'll check it

**Pull request merged**
